#
#
# NESS Reloaded v2 Configuration
#
#

#
#
# Enabled checks
#
# Comment out a check to disable
#

enabled-checks:
  - 'AutoClick'
  - 'AntiASCII'
  - 'AntiKb'
  - 'AutoClicker'
#  - 'BadPackets'
  - 'Criticals'
  - 'EntitySpeedCheck'
  - 'FastEat'
  - 'FastPlace'
#  - 'FastStairs'
  - 'Fly'
  - 'GhostHand'
  - 'Headless'
  - 'IllegalInteraction'
  - 'InventoryHack'
  - 'Jesus'
  - 'Killaura'
  - 'KillauraBotCheck'
  - 'NoClip'
  - 'NoSlowDownBow'
  - 'NoSlowDownFood'
  - 'NoSwingAnimation'
  - 'NoSwingAttack'
  - 'PatternKillauraAttack'
  - 'PatternKillauraMove'
  - 'Scaffold'
  - 'SpamBot'
  - 'Speed'
  - 'Sprint'

#
# Check name
#
# Performance impact: minimal, low, medium, high
# Effectiveness: medium, high, very high
#

checks:

#
# AutoClick
#
# Performance impact: Minimal
# Effectiveness: ?
#
  autoclick:
    total-retention-secs: 32
    hard-limit:
      cps: 16
      retention-span-secs: 4
    constancy:
      threshold: 4
      deviation-percent: 20
      min-sample: 6
      super:
        deviation-percent: 10
        min-sample: 12
      span-millis: 800

# If you change this, you will receive warnings in console
config-version: 1