name: NESS
main: org.mswsplex.MSWS.NESS.NESS
version: 1.9
author: herobrine99dan
softdepend: [ProtocolLib, Punish, mcMMO]
commands:
   ness:
      description: Made by MSWS
      usage: /<command>