#
#
# NESS Reloaded v2 Configuration
#
#

#
#
# General settings
#
dev-mode: false

#
#
# Violation handling
#
# What to do when a player is detected
#
violation-handling:
  notify-staff:
    enable: true
    vl: 6
    discord-webhook: ''
    notification: '&8[&b&lNESS&8]&r&7> &c%PLAYER% &7failed &c%HACK%&7. VL %VL% Details: %DETAILS%'
  cancel:
    enable: true
    vl: 3
  execute-command:
    enable: true
    vl: 20
    command: 'kick %PLAYER% Please Do not use Cheats! If you think this is an error, contact staff'

#
#
# Enabled checks
#
# Comment out a check to disable
#

enabled-checks:
  - 'Aimbot'
  - 'AutoClicker'
  - 'AntiBot'
  - 'AntiBotWhitelist'
  - 'AntiUnicode'
  - 'AntiKb'
  - 'BadPackets'
  - 'BlockBreakChecks'
  - 'Criticals'
  - 'FastEat'
  - 'FastPlace'
  - 'ChestESP'
  - 'FastStairs'
  - 'Fly'
  - 'GhostHand'
  - 'Headless'
  - 'TeleportEvent'
  - 'LiquidInteraction'
  - 'NameExploit'
  - 'InventoryHack'
  - 'Jesus'
  - 'Killaura'
  - 'KillauraFalseFlying'
  - 'Hitbox'
  - 'MorePackets'
  - 'NoSlowDownBow'
  - 'NoSlowDownFood'
  - 'NameExploit'
  - 'OldMovementChecks'
  - 'Scaffold'
  - 'SpamBot'
  - 'Speed'
  - 'PingSpoof'
  - 'Strafe'
  - 'TeleportEvent'

#
# Check name
#
# Description
#
# Performance impact: minimal, low, medium, high
# Effectiveness: medium, high, very high
#

checks:

#
# AutoClick
#
# Caps clicks per second (CPS) at a hard limit, also calculates
# the variance in the user's clicks (constancy) and the variance
# in the variance (constancy super).
#
# Performance impact: Minimal
# Effectiveness: untested
#
  autoclick:
      # Clicks older than this are completely ignored
    total-retention-secs: 32
    # A basic CPS cap
    hard-limit:
      # These are pairs of CPS limits and required time spans
      #
      # If the player's CPS measured over the time span is greater than the CPS limit, a violation is triggered.
      #
      # For example, '16:3' means that if the player's clicks in the past 3 seconds average 16 CPS, trigger a violation.
      cps-and-required-span:
        - '16:3'
        - '16:1'
    # A more advanced consistency check
    constancy:
      # These are pairs of standard deviation percentages and sample counts
      #
      # The standard deviation is calculated based on the interval between clicks in the sample.
      # The second number in the pair determines the sample size.
      # Then, the standard deviation percentage is calculated as the standard deviation as percent of the average.
      # If this percent is less than the first number in the pair, a violation is triggered.
      #
      # For example, '30:8' means that if the standard deviation in the interval between clicks over a sample
      # of 8 intervals, divided by the average interval, is greater than 30%, trigger a violation.
      deviation-and-sample:
        - '30:8'
        - '15:16'
      # These are pairs of standard deviation percentages and sample counts
      #
      # These are conceptually similar to the previous. However, this measures the standard deviations between
      # the standard deviations. Thus, it is called the "super deviation".
      superdeviation-and-supersample:
        - '10:8'
      span-millis: 800

#
# LiquidInteraction
#
# Checks to see if a player placed a block against water.
#
# Performance impact: Minimal
# Effectiveness: High
#
  liquidinteraction:
    whitelisted-materials:
      - 'WATER_LILY'
    

# If you change this, you will receive warnings in console
config-version: 1