name: NESS
main: com.github.ness.NESSAnticheat
version: ${project.version}
authors: [herobrine99dan, A248]
softdepend: [ProtocolLib]
commands:
   ness:
      description: Main ness command
      usage: /<command>