name: NESS
main: com.github.ness.NESSAnticheat
version: ${project.version}
authors: [herobrine99dan, A248]
softdepend: [ProtocolLib]
description: 'A free, open-source anticheat which seeks to block hackers with simple yet effective checks.'

commands:
  ness:
    description: Main ness command
    usage: /<command>